### ISSUE TITLE
subview 的管理似乎有些问题

### ISSUE THREAD

**Issue by lightory** [levey/LeveyTabBarController#1]
目前的设计：点击某个 tab 后，前一个 view 是被覆盖的，并没有被 remove。

这样会导致一些问题：
- 第二次点击某一个 tab 时，对应的 viewWillAppear 和 viewDidAppear 等方法不会被调用。
- 如果每个 Tab 都对应一个 tableViewController，对导致点击 statusBar 回到顶部的功能失效。

**Comment by levey** [comment]
抽空改下这问题，刚看到这个 issue 不好意思。

**Comment by lightory** [comment]
:)

**Comment by levey** [comment]
fixed
